// <auto-generated />
using System;
using Humo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Humo.Api.Data.Migrations
{
    [DbContext(typeof(HumoDbContext))]
    partial class HumoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Humo.Api.Data.AccountSequenceRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId");

                    b.ToTable("AccountSequences");
                });

            modelBuilder.Entity("Humo.Api.Data.CookAnalyticsRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("DurationHours")
                        .HasColumnType("float");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("FuelEfficiency")
                        .HasColumnType("float");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("bit");

                    b.Property<int>("MeatType")
                        .HasColumnType("int");

                    b.Property<double?>("PitStabilityScore")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("StallEndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("StallHours")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("StallStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("TimePerKg")
                        .HasColumnType("float");

                    b.HasKey("AccountId", "CookId");

                    b.HasIndex("AccountId", "MeatType", "EquipmentId");

                    b.ToTable("CookAnalytics");
                });

            modelBuilder.Entity("Humo.Api.Data.CookRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AmbientTempC")
                        .HasColumnType("float");

                    b.Property<bool>("ClockSkewFlagged")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FinishReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MeatType")
                        .HasColumnType("int");

                    b.Property<string>("MeatTypeOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PitType")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("TargetInternalTempC")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("AccountId", "Id");

                    b.HasIndex("AccountId", "Sequence");

                    b.ToTable("Cooks");
                });

            modelBuilder.Entity("Humo.Api.Data.DeviceCursorRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Cursor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountId", "DeviceId");

                    b.ToTable("DeviceCursors");
                });

            modelBuilder.Entity("Humo.Api.Data.EntitlementRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastEventAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastEventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreSubscriberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountId");

                    b.ToTable("Entitlements");
                });

            modelBuilder.Entity("Humo.Api.Data.EquipmentRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ClockSkewFlagged")
                        .HasColumnType("bit");

                    b.Property<double?>("CookChamberVolumeL")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("FireboxVolumeL")
                        .HasColumnType("float");

                    b.Property<int>("Insulation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountId", "Id");

                    b.HasIndex("AccountId", "Sequence");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Humo.Api.Data.EventRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ClockSkewFlagged")
                        .HasColumnType("bit");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountId", "Id");

                    b.HasIndex("AccountId", "Sequence");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Humo.Api.Data.FuelEventRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ClockSkewFlagged")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("SizeClass")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ViaNotification")
                        .HasColumnType("bit");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.Property<int>("WoodType")
                        .HasColumnType("int");

                    b.Property<string>("WoodTypeOther")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId", "Id");

                    b.HasIndex("AccountId", "Sequence");

                    b.ToTable("FuelEvents");
                });

            modelBuilder.Entity("Humo.Api.Data.PitTempEntryRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AmbientTempC")
                        .HasColumnType("float");

                    b.Property<bool>("ClockSkewFlagged")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PitTempC")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountId", "Id");

                    b.HasIndex("AccountId", "Sequence");

                    b.ToTable("PitTempEntries");
                });

            modelBuilder.Entity("Humo.Api.Data.TempEntryRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ClockSkewFlagged")
                        .HasColumnType("bit");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MeatTempC")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountId", "Id");

                    b.HasIndex("AccountId", "Sequence");

                    b.ToTable("TempEntries");
                });

            modelBuilder.Entity("Humo.Api.Data.UserBaselineRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MeatType")
                        .HasColumnType("int");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Mean")
                        .HasColumnType("float");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("float");

                    b.HasKey("AccountId", "MeatType", "EquipmentId", "Metric");

                    b.ToTable("UserBaselines");
                });
#pragma warning restore 612, 618
        }
    }
}
